### ISSUE TITLE
Can't run project on M1 Mac

### ISSUE THREAD

**Issue by Kiho** [VICTORVICKIE/sql-notebook#2]
I am getting error when build.
`path matching bin/sqlite3-aarch64-apple-darwin not found.`
Any solution for this?

**Comment by VICTORVICKIE** [comment]
@Kiho Sorry for late reply, I didnt have a mac for testing and compiling, i ll follow up on this with the instructions for you to add it yourself, if you wish you can make a pull request after compiling this app, so i can add it to release.

**Comment by VICTORVICKIE** [comment]
Tauri Sidecar: [https://tauri.app/v1/guides/building/sidecar/](https://tauri.app/v1/guides/building/sidecar/)

Add the Suitable SQLite binary here
[sql-notebook/src-tauri/bin/](https://github.com/VICTORVICKIE/sql-notebook/tree/master/src-tauri/bin)

This is the source page for sqlite, you might need to build it yourself using make
[https://www.sqlite.org/download.html](https://www.sqlite.org/download.html)

**Comment by Kiho** [comment]
Thanks for help. don't need compile the source. I was able to install sqlite on machine with `brew install sqlite` then copy binary file from `/opt/homebrew/opt/sqlite/bin` to `src_tauri/bin`. Rename file `sqlite3` to `sqlite3-aarch64-apple-darwin` made thing work.

**Comment by VICTORVICKIE** [comment]
@Kiho , Thanks for the PR, I ll look into cross-compilation and try to make github action.
